### ISSUE TITLE
Cannot run container on Ubuntu 22.04 ARM in Parallels on M3 MacBook Pro

### ISSUE THREAD

**Issue by vanackera** [balena-os/iot-gate-imx8plus-flashtools#3]
When I try to follow the instructions and run the container, I get the following error:
`ERROR: failed to solve: process "/bin/sh -c apt-get update && apt-get install -y libusb-1.0-0-dev libbz2-dev libzstd-dev pkg-config cmake libssl-dev g++ zlib1g-dev git usbutils file &&     git clone https://github.com/nxp-imx/mfgtools.git && cd mfgtools && git checkout 3a5beb69a3b0e8dcb78bd6a8fabd77f2ebe6018f &&     cmake -S . -B build  &&     cmake --build build --target all" did not complete successfully: exit code: 1
`
Doing the exact same thing on Ubuntu 22.04 in Parallels on an Intel MacBook Pro does correctly build the container and flashes the devices. My access to Intel based Macs is rather limited, so I would prefer to be able have it working on Apple Silicon too.
Thanks!

**Comment by acostach** [comment]
Hi @vanackera,

I don't have access a Mac to test with but in the automated test setup we use Pi3s to run the flashing container, and for that we build the Dockerfile using an [armv7 base image](https://github.com/balena-os/iot-gate-imx8plus-flashtools/blob/master/run_container.sh#L62). So if the Mac uses an ARM chip it's possible that building the Dockerfile with an aarch64 base image may work

**Comment by acostach** [comment]
Hi @vanackera , does the above work for you?

**Comment by vanackera** [comment]
Hi, I did try running `./run_container -a armv7`, but that generated the error as described in the issue.
I also logged a support ticket through BalenaCloud support and they suggested I change the first line of the Dockerfile to: `ARG RT=aarch64-ubuntu:focal-run-20221215`.
Running `./run_container` after that change, correctly builds and runs the container, both on my virtualised Ubuntu as on the host MacOS.
I'll report back once I tested flashing a device.

**Comment by vanackera** [comment]
Reporting back:
I can flash the device from Ubuntu in Parallels on M3 Apple Silicon.
Directly from MacOS it doesn't work, I get:
```
[INFO] Using bootloader compatible with 2GB and 4GB DRAM versions of IOT-GATE-iMX8PLUS
[INFO] OS release major version is 5
[INFO] imx-boot-iot-gate-imx8plus-sd.bin-flash_evk has been extracted
uuu (Universal Update Utility) for nxp imx chips -- libuuu_1.5.141-3-g3a5beb6

Wait for Known USB Device Appear...
```
I think this has something to do with the results of lsusb on MacOS.
In the container I only get 2 devices: 'Linux Foundation 3.0 root hub' and 'Linux Foundation 2.0 root hub' .
Directly on my OS (after installing with brew install usbutils) I get 5 devices (IDs like '0bda:8153' only).

**Comment by acostach** [comment]
Hi, thanks for confirming and glad to hear flashing works now from Ubuntu on Parallels!

**Comment by acostach** [comment]
If you wish @vanackera  , you can push a commit to support this directly by adding `-a aarch64`  in https://github.com/balena-os/iot-gate-imx8plus-flashtools/blob/master/run_container.sh#L62 to use the image tag that works for you

**Comment by acostach** [comment]
Added aarch64 build option in https://github.com/balena-os/iot-gate-imx8plus-flashtools/pull/5
